/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.ts"],
    daisyui: {
        themes: [
            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            "dim",
            "nord",
            "sunset",
            {
                mytheme: {
                    "primary": "#fde68a",
                    "secondary": "#f472b6",
                    "accent": "#075985",
                    "neutral": "#0284c7",
                    "info": "#8be8fd",
                    "success": "#52fa7c",
                    "warning": "#fb923c",
                    "error": "#ff5757",
                    "base-100": "#fafafa",
                },
            },
        ],
    },
    theme: {
        extend: {},
    },
    plugins: [
        require('@tailwindcss/typography'),
        require("daisyui"),
    ],
}

